/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileManager */

#ifndef _Included_FileManager
#define _Included_FileManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileManager
 * Method:    selectFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FileManager_selectFile
  (JNIEnv *, jobject);

/*
 * Class:     FileManager
 * Method:    saveFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileManager_saveFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
